plugins:
  - "@dotcom-tool-kit/component"
  - '@dotcom-tool-kit/husky-npm'
  - '@dotcom-tool-kit/lint-staged-npm'
  - "@dotcom-tool-kit/mocha"
hooks:
  git:precommit:
    - LintStaged
options:
  '@dotcom-tool-kit/circleci':
    nodeVersion:
      - '20.11'
      - '18.19'
      - '16.20'
